### ISSUE TITLE
不需要填入目标的仓库名称地址吗

### ISSUE THREAD

**Issue by 1438343098** [yibei333/sync-github-release-to-gitee#1]
{"GiteeToken":"***","GithubToken":"***","Repo":"1438343098\/tweets-manage"}
RemoveExistHandle start
RemoveExistHandle failed:get release list failed:{"message":"Not Found Project"}
Unhandled Exception: System.Exception: get release list failed:{"message":"Not Found Project"}
   at SyncGithubReleaseToGitee.Handlers.Common.BaseHandle.Handle()
   at SyncGithubReleaseToGitee.Program.Main()
   
   使用报错

**Comment by yibei333** [comment]
根据代码显示的地址是 https://gitee.com/api/v5/repos/1438343098/tweets-manage/releases ,确实是找不到呢,你的仓库地址是啥
``` csharp
https://gitee.com/api/v5/repos/{Context.Parameter.Repo}/releases?access_token={Context.Parameter.GiteeToken}
```

**Comment by yibei333** [comment]
需要手动在gitee里面创建github的镜像仓库哦，这个工具仅仅是将最新的release同步到gitee里面（gitee有文件大小限制，所以会删除旧的release以释放文件），不会同步代码过去
